name: 1.0.$(Rev:r)

pr:
  branches:
    include:
    - '*'
  paths:
    include:
    - '.azure/*'

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - '.azure/*'

pool:
    vmImage: ubuntu-latest

variables:
  ismaster: $[eq(variables['Build.SourceBranch'], 'master')]


steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.9
    displayName: Use Python 3.9

  - task: PipAuthenticate@1
    displayName: 'Pip authenticate'
    inputs:
      artifactFeeds: 'pypy'
      onlyAddExtraIndex: True   # 'onlyAddExtraIndex' also populates PIP_EXTRA_INDEX_URL env variable

  - script: |
      python -m pip install --upgrade pip
      pip install artifacts-keyring
      pip install -r devrequirements.txt --extra-index-url https://pkgs.dev.azure.com/FinitiveLLC/Finitive/_packaging/pypy/pypi/simple/
    displayName: "Install requirements"
    workingDirectory: $(System.DefaultWorkingDirectory)

  - script: |
      source .env/bin/activate
      pip install -r devrequirements.txt
      python runtests.py --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html
    displayName: "Run Unit test"
    workingDirectory: $(System.DefaultWorkingDirectory)

  - task: PublishTestResults@2
    condition: succeeded()
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: $(System.DefaultWorkingDirectory)/junit/test-*.xml
      testRunTitle: 'Publish test results'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage.xml'

  - script: |
      python setup.py sdist
    displayName: 'Artifact creation'

  - script: |
      pip install twine
      pip install wheel
    workingDirectory: $(System.DefaultWorkingDirectory)
    displayName: "Install twine"
    condition: eq(variables.ismaster, true)
    
  - task: TwineAuthenticate@1
    inputs:
      artifactFeed: Finitive/pypy
    displayName: Twine Authenticate
    condition: eq(variables.ismaster, true)

  - script: |
      python setup.py sdist bdist_wheel
      twine upload -r pypy --config-file $(PYPIRC_PATH) dist/* --non-interactive --skip-existing --verbose
    displayName: "Upload Artifacts"
    workingDirectory: $(System.DefaultWorkingDirectory)
    condition: eq(variables.ismaster, true)